version: '3'
services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./api
    image: api.saastr
    restart: always
    ports:
      - 3333:3333
    expose:
      - "3333"
    environment:
      - ENV_PATH=/api/.env
      - NODE_ENV=production
      - VIRTUAL_HOST=api.saastr.0x0.run
      - LETSENCRYPT_HOST=api.saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=3333
    volumes:
      - ./api:/api

  app:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./app
    image: app.saastr
    restart: always
    ports:
      - 3000:3000
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=saastr.0x0.run
      - LETSENCRYPT_HOST=saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=3000

  postgres:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=azertyuiop
      - POSTGRES_DB=saastr
      - VIRTUAL_HOST=db.saastr.0x0.run
      - LETSENCRYPT_HOST=db.saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=5432
    volumes:
      - ./database:/var/lib/postgresql/data
