version: '3'
services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./api
    image: api.saastr
    restart: always
    ports:
      - 3333:3333
    expose:
      - "3333"
    environment:
      - ENV_PATH=/api/.env
      - NODE_ENV=production
      - VIRTUAL_HOST=api.saastr.0x0.run
      - LETSENCRYPT_HOST=api.saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=3333
    network_mode: bridge

  app:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./app
    image: app.saastr
    restart: always
    ports:
      - 3000:3000
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=saastr.0x0.run
      - LETSENCRYPT_HOST=saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=3000
    network_mode: bridge
    depends_on:
      - api

  postgres:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: postgres
    ports:
      - 5433:5432
    expose:
      - "5433"
    environment:
      - DEBUG=false
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=XXXXXX
      - POSTGRES_DB=saastr
      - VIRTUAL_HOST=db.saastr.0x0.run
      - LETSENCRYPT_HOST=db.saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=5433
    network_mode: bridge
    volumes:
      - ./database:/var/lib/postgresql/data

  documentation:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: nginx
    ports:
      - 8080:80
    expose:
      - "8080"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
